#!/usr/bin/env python3
import json
import sys
from collections import defaultdict
from pathlib import Path

repo=Path(__file__).resolve().parents[1]
jp=repo/'docs/specs/2026-07-23-oem-movement-method-source-binary-registry.json'
out=repo/'docs/specs/2026-07-23-oem-movement-method-source-binary-registry.md'
d=json.loads(jp.read_text())
lines=[]
a=lines.append
a('# BioXP3200 serial-206 OEM movement method/source/binary registry')
a('')
a('**Date:** 2026-07-23')
a(f"**Schema:** `{d['schema_id']}`")
a('**Authority:** recovered OEM source/binaries and the canonical evidence lock only')
a('**Physical action:** none; this is a static evidence registry')
a('')
a('## 1. Purpose and claim boundary')
a('')
a(d['scope'])
a('')
a(f"**Claim boundary:** {d['claim_boundary']}")
a('')
a('This registry closes source-discovery for the startup movement envelope. `present_hash_locked_and_line_bounded` means the source bytes, captured binary, and inclusive source lines are pinned; it does **not** mean the Linux implementation or physical machine behavior has been accepted.')
a('')
a('The canonical corpus must be searched before any absence statement. `unreviewed`, `not yet line-locked`, `not implemented`, and `not physically validated` are not synonyms for `absent`.')
a('')
a('## 2. Controlling evidence')
a('')
a(f"- Evidence lock: `{d['authority']['evidence_lock_path']}`")
a(f"- Lock schema: `{d['authority']['evidence_lock_schema']}`")
a(f"- Evidence-lock SHA-256: `{d['authority']['evidence_lock_sha256']}`")
a(f"- Acquisition: `{d['authority']['acquisition_session_id']}`")
a(f"- Frozen SSD manifest SHA-256: `{d['authority']['frozen_ssd_manifest_sha256']}`")
a(f"- Machine: BioXP3200 serial `206`")
a(f"- Registry JSON: `{jp.relative_to(repo)}`")
a('')
a('## 3. Captured OEM binaries')
a('')
a('| Binary | SHA-256 | Bytes | Exact path |')
a('|---|---|---:|---|')
for b in d['binaries']:
 a(f"| `{b['binary_id']}` | `{b['sha256']}` | {b['size']} | `{b['path']}` |")
a('')
a('## 4. Recovered source-to-binary map')
a('')
a('| Source ID | Recovered source | SHA-256 | Lines | Captured binary | Map status | Mapping evidence |')
a('|---|---|---|---:|---|---|---|')
for s in d['sources']:
 ev=s['binary_mapping_evidence']; loc=ev['path'] + (f":{ev['line']}" if ev.get('line') else '')
 a(f"| `{s['source_id']}` | `{s['relative_path']}` | `{s['sha256']}` | {s['line_count']} | `{s['binary_id']}` | `{s['binary_map_status']}` | `{ev['kind']}: {loc}` |")
a('')
a('Every listed source-to-binary relationship is backed either by the canonical evidence-lock `decompile_binary_map` or by an exact frozen-SSD manifest assembly-root record. Project metadata alone cannot satisfy registry admission.')
a('')
a('## Canonical named deck action source closure')
a('')
denominator=d['finite_destination_denominator']
a(f"The finite operator denominator contains **{denominator['panel_label_count']}** panel labels, **{denominator['distinct_location_id_count']}** distinct location IDs, and **{denominator['configured_position_table_row_count']}** configured PositionTable rows.")
a('Pinned raw IL closes the barcode-offset and Park branches only; unrelated vision algorithms remain unresolved.')
a('')
a('## 5. Selected serial-206 configuration provenance')
a('')
c=d['selected_machine_configuration']
a(f"- `config.xml`: `{c['config_sha256']}`")
a(f"- `Operation_parameters.xml`: `{c['operation_parameters_sha256']}`")
a(f"- `InspectionSettings.xml`: `{c['inspection_settings_sha256']}`")
a('')
a('| Field | Selected value | Artifact | Exact line(s) | Selector |')
a('|---|---|---|---|---|')
for r in c['field_records']:
 loc=str(r.get('line',r.get('line_range')))
 val=json.dumps(r['value'],sort_keys=True).replace('|','\\|')
 a(f"| `{r['field']}` | `{val}` | `{r['artifact']}` | `{loc}` | `{r['selector']}` |")
a('')
a('The selected `PositionTable` is exactly lines 30–60 of `config.xml`: 29 entries, including all startup, cover, camera, press, waste, and park coordinates. It is data, not a future acquisition gap.')
a('')
a('## 6. Exact method/member registry')
a('')
a(f"Total line-bounded methods/members: **{d['counts']['methods_and_members']}**.")
a('')
by=defaultdict(list)
for m in d['methods']: by[m['source_id']].append(m)
source_by={s['source_id']:s for s in d['sources']}
for sid in sorted(by):
 s=source_by[sid]
 a(f"### 6.{len([x for x in sorted(by) if x <= sid])} `{s['relative_path']}`")
 a('')
 a(f"Source SHA-256: `{s['sha256']}`")
 a(f"Captured binary: `{s['binary_id']}`")
 a('')
 a('| Method/member ID | Inclusive lines | Declaration/member | Literal sleeps | Decompiler warning lines |')
 a('|---|---:|---|---|---|')
 for m in by[sid]:
  sleeps=', '.join(f"L{x['line']}={x['milliseconds']}ms" for x in m['literal_sleeps']) or '—'
  warns=', '.join(str(x) for x in m['decompiler_warning_lines']) or '—'
  decl=m['declaration'].replace('|','\\|')
  a(f"| `{m['method_id']}` | `{m['start_line']}–{m['end_line']}` | `{decl}` | {sleeps} | {warns} |")
 a('')
a('## 7. Required transitive call edges')
a('')
a('| Edge ID | Exact caller | Exact callee/member | Call line | Source token |')
a('|---|---|---|---:|---|')
for e in d['required_call_edges']:
 a(f"| `{e['edge_id']}` | `{e['caller_method_id']}` | `{e['callee_method_id']}` | {e['call_line']} | `{e['callee_token']}` |")
a('')
a('Each edge is independently checked against the caller’s exact line range and source text. These are not name-only anchors: overload identity, caller identity, call line, and callee/member identity are all pinned.')
a('')
a('## 8. Required startup branch and terminal outcomes')
a('')
a('| Branch ID | Exact caller | Line | Required source token | OEM outcome |')
a('|---|---|---:|---|---|')
for b in d.get('required_branch_outcomes',[]):
 a(f"| `{b['branch_id']}` | `{b['caller_method_id']}` | {b['line']} | `{b['token']}` | {b['outcome']} |")
a('')
a('These entries preserve OEM branch facts, including CAN-not-ready terminal exits. They do not authorize motion and must map to explicit Linux terminal lifecycle states before any remote implementation is admitted.')
a('')
a('## 9. Ordered source sequences')
a('')
for seq in d['ordered_call_sequences']:
 a(f"### `{seq['sequence_id']}`")
 a('')
 a(f"Caller: `{seq['caller_method_id']}`")
 a('')
 a('| Order | Exact line | Required source token |')
 a('|---:|---:|---|')
 for n,step in enumerate(seq['steps'],1): a(f"| {n} | {step['line']} | `{step['token']}` |")
 a('')
a('## 10. Named source hazards and mandatory disposition')
a('')
a('| Hazard ID | Source reference | Mandatory disposition | Detail |')
a('|---|---|---|---|')
for h in d['known_hazards']:
 a(f"| `{h['hazard_id']}` | `{h['source_ref']}` | `{h['disposition']}` | {h['detail']} |")
a('')
a('These are present-source hazards, not acquisition gaps. No hazard may be silently normalized into an inferred Linux behavior; it requires the recorded binary disposition or an explicit, reviewed fail-closed safety deviation.')
a('')
a('## 11. Decompiler/binary-review boundary')
a('')
a('Decompiler warning lines are recorded per method instead of being hidden. Before implementing any warning-bearing authority method, the tranche must resolve the affected predicate/control flow against the pinned captured binary or preserve a fail-closed blocker. Native `CVisionLib` projections must be tested against the captured DLL and templates; they must not be rewritten from apparent decompiler output alone.')
a('')
a('## 12. Registry acceptance rules')
a('')
a('The registry is accepted only when automated validation proves:')
a('')
a('1. every source and binary hash matches the file at the exact recorded path;')
a('2. every method declaration exists at its recorded start line and the end line remains brace-bounded;')
a('3. every source-to-binary claim is present in the canonical evidence-lock map, and the registry pins the lock schema, acquisition session, and exact lock SHA-256;')
a('4. all required startup call-graph anchors and exact transitive caller→callee edges are present;')
a('5. every required startup branch and terminal outcome is line-pinned and source-token verified;')
a('6. the exact 19-file live machine corpus remains closed-world and hash-valid;')
a('7. serial-206 configuration values match the recorded XML field identity, exact attribute/value, and derivation anchors;')
a('8. all registered ordered sequences have strictly increasing exact source lines and required tokens;')
a('9. no method is promoted from static authority to implemented, controller-validated, or physically validated without separate evidence.')
a('')
a('## 13. Explicitly closed false gaps')
a('')
a('- Lower `ClassPipette` command/reply bodies: present and line-bounded.')
a('- `InterfaceCAN`, `ClassNovo`, and `ClassNovoCANUSB` routing: present and line-bounded.')
a('- `Novo.Devices` packet shape, big-endian module ID, DLC, escaping/framing/checksum, USB bulk write/read, and reconnect helpers: present and line-bounded.')
a('- Board and motor primitives: present and line-bounded.')
a('- Route bodies and the selected 29-entry `PositionTable`: present and line-bounded/hash-locked.')
a('- Camera/cover callers, native vision binary, inspection settings, and templates: present/hash-locked.')
a('- Chiller/thermal transport and calibration: present and line-bounded/hash-locked.')
a('- Serial-206 configuration selection: closed-world and hash-locked.')
a('')
a('The remaining work is implementation, semantic equivalence testing, controller validation, interlock validation, and separately authorized physical acceptance—not source discovery.')
rendered='\n'.join(lines)+'\n'
if '--check' in sys.argv:
 if not out.is_file() or out.read_text()!=rendered:
  raise SystemExit(f'rendered registry drift: {out}')
else:
 out.write_text(rendered)
print(out)
print('lines',len(lines))
